from __future__ import annotations

import random
import numpy as np
from collections import defaultdict, Counter
from typing import Any, Callable, Dict, List, Optional, Tuple, Iterable, Set

from qiskit import QuantumCircuit

try:
    from qiskit import qasm2
except Exception:
    qasm2 = None

from structure import Circuit, GateSet, update_ngrams, update_conditional_results


# Convert quantum circuit to string using qasm2 (normally)
def circuit_to_key(qc: QuantumCircuit) -> str:
    if qasm2 is not None:
        return qasm2.dumps(qc)
    if hasattr(qc, "qasm"):
        print("used qasm instead of qasm2, old quiskit version")
        return qc.qasm()
    print("no qasm available")
    return str(qc)


# Use normalize_coupling_map from structure.Gateset
def normalize_coupling_map(
    coupling_map: Optional[Iterable[Tuple[int, int]]],
    directed_coupling: bool,
) -> Set[Tuple[int, int]]:
    return GateSet._normalize_coupling_map(coupling_map, directed_coupling)


# return the max number of children a node is allowed to expand
# Use boolean branches = false to use progressive widening
def pw_max_children(node: "Node", branches, pw_C: float, pw_alpha: float) -> int:
    if isinstance(branches, bool):
        if branches:
            raise NotImplementedError("Double progressive widening is not implemented yet.")
        t = max(int(node.visits), 1)
        return max(1, int(np.ceil(pw_C * (t ** pw_alpha))))
    elif isinstance(branches, int):
        return int(branches)
    else:
        raise TypeError("The 'branches' parameter must be an int or bool.")


# return how many more children the node is allowed to expand
# (according to progressive widening if branches = false)
def pw_available_slots(node: "Node", branches, pw_C: float, pw_alpha: float) -> int:
    k = pw_max_children(node, branches, pw_C, pw_alpha)
    return max(0, k - len(node.children))


class Node:
    def __init__(
            self,
            state: Circuit,
            max_depth: int,
            parent=None,
            coupling_map: Optional[Iterable[Tuple[int, int]]] = None,
            directed_coupling: bool = True,
    ):
        self.state = state
        self.isTerminal = False
        self.parent = parent
        self.children: List["Node"] = []
        self.visits = 0
        self.value = 0.0
        self.max_depth = max_depth
        self.tree_depth = 0 if parent is None else parent.tree_depth + 1

        # Backend basis gate set
        self.gate_set = "backend"

        self.stop_is_done = False
        self.action = None
        self.counter_cx = self.state.circuit.count_ops().get("cx", 0)

        # Coupling map support
        self.directed_coupling = bool(directed_coupling)
        if parent is not None:
            self.coupling_map: Set[Tuple[int, int]] = set(parent.coupling_map)
            self.directed_coupling = bool(parent.directed_coupling)
        else:
            self.coupling_map = normalize_coupling_map(coupling_map, self.directed_coupling)

        # Optional GNN prior information
        self.prior_value: Optional[float] = None

    def __repr__(self):
        return (
            f"Tree depth: {self.tree_depth}  -  Generated by Action: {self.action}  -  "
            f"Number of Children: {len(self.children)}  -  Visits: {self.visits}  -  "
            f"Value: {self.value}   -  "
            f"CouplingEdges: {len(self.coupling_map)}  -  "
            f"Quantum Circuit (CNOT counts)= {self.counter_cx}):\n{self.state.circuit}"
        )

    def _make_gateset(self) -> GateSet:
        return GateSet(
            self.gate_set,
            coupling_map=self.coupling_map,
            directed_coupling=self.directed_coupling,
        )

    def is_fully_expanded(self, branches, pw_C, pw_alpha):
        return pw_available_slots(self, branches, pw_C, pw_alpha) == 0

    def define_children(self, prob_choice, stop_deterministic, roll_out: bool = False):
        parent = self
        qc = parent.state.circuit.copy()
        stop = self.stop_is_done if not roll_out else True
        gate_set = parent._make_gateset()

        def det_stop():
            new_qc, action = parent.state.get_legal_action(
                gate_set, self.max_depth, prob_choice, stop
            )
            new_qc = new_qc(qc)

            if new_qc is None:
                temporary_prob_choice = {"a": 50, "s": 50, "c": 0, "d": 0}
                new_qc, action = parent.state.get_legal_action(
                    gate_set, self.max_depth, temporary_prob_choice, stop
                )
                new_qc = new_qc(qc)

            new_node = node_from_qc(new_qc, parent_node=self, roll_out=roll_out)
            new_node.action = action
            self.counter_cx = self.state.circuit.count_ops().get("cx", 0)
            return new_node

        def prob_stop():
            new_qc, action = parent.state.get_legal_action(
                gate_set, self.max_depth, prob_choice, stop
            )
            new_qc = new_qc(qc)

            if new_qc == "stop":
                self.isTerminal = True
                self.stop_is_done = True
                self.counter_cx = self.state.circuit.count_ops().get("cx", 0)
                return self

            if new_qc is None:
                temporary_prob_choice = {"a": 50, "s": 50, "c": 0, "d": 0}
                new_qc, action = parent.state.get_legal_action(
                    gate_set, self.max_depth, temporary_prob_choice, stop
                )
                new_qc = new_qc(qc)

                if new_qc is None:
                    temporary_prob_choice = {"a": 100, "s": 0, "c": 0, "d": 0}
                    new_qc, action = parent.state.get_legal_action(
                        gate_set, self.max_depth, temporary_prob_choice, stop
                    )
                    new_qc = new_qc(qc)

            if isinstance(new_qc, QuantumCircuit):
                new_state = Circuit(new_qc.num_qubits, new_qc.num_clbits).building_state(new_qc)
                new_node = Node(
                    new_state,
                    max_depth=self.max_depth,
                    parent=self,
                    coupling_map=self.coupling_map,
                    directed_coupling=self.directed_coupling,
                )
                new_node.action = action
                self.counter_cx = self.state.circuit.count_ops().get("cx", 0)
                if not roll_out:
                    self.children.append(new_node)
                return new_node

            raise TypeError(
                f"Expected QuantumCircuit, got {type(new_qc)} "
                f"(action={action}, value_repr={repr(new_qc)[:200]})"
            )

        return det_stop() if stop_deterministic else prob_stop()

    def best_child(self, criteria: str):
        children_with_values = [(child, child.value, child.visits) for child in self.children]
        if criteria == "value":
            return max(children_with_values, key=lambda x: x[1])[0]
        if criteria == "average_value":
            return max(children_with_values, key=lambda x: x[1] / max(x[2], 1))[0]
        if criteria == "visits":
            return max(children_with_values, key=lambda x: x[2])[0]
        raise ValueError("criteria must be one of: visits, value, average_value")

    # Not revised, no simulation in the thesis
    def simulation(self, simulation_strategy, qubit: int):
        """
        Simulates most likely gates for a qubit based on n-gram conditional probabilities.

        In backend mode, CX must respect the coupling map.
        """
        qc = self.state.circuit.copy()

        ngrams_quality = simulation_strategy[qubit]
        last_gate = qc.data[-1][0].name if qc.data else None

        gates_ngram, quality_ngram = [], []
        for ngram, quality_scores in ngrams_quality.items():
            if isinstance(ngram, tuple) and last_gate in ngram[-1]:
                gates_ngram.append(ngram[0])
                quality_ngram.append(quality_scores[0])

        quality_ngram = [-q if q < 0 else 0 for q in quality_ngram]
        if len(quality_ngram) > 0:
            norm = np.linalg.norm(quality_ngram)
            if norm > 0:
                quality_ngram = quality_ngram / norm

        if gates_ngram and sum(quality_ngram) > 0:
            next_gate = random.choices(gates_ngram, weights=quality_ngram, k=1)[0]
            gate_set = self._make_gateset()

            if next_gate == "rz":
                qc.rz(random.uniform(0, 2 * np.pi), qubit)
            elif next_gate == "sx":
                qc.sx(qubit)
            elif next_gate == "x":
                qc.x(qubit)
            elif next_gate == "cx":
                legal_edges = gate_set.legal_cx_edges(qc.num_qubits)
                edge_candidates = [e for e in legal_edges if qubit in e]
                if edge_candidates:
                    edge = random.choice(edge_candidates)
                    qc.cx(edge[0], edge[1])

        new_state = Circuit(qc.num_qubits, qc.num_clbits).building_state(qc)
        return Node(
            new_state,
            max_depth=self.max_depth,
            parent=self,
            coupling_map=self.coupling_map,
            directed_coupling=self.directed_coupling,
        )


def make_root_node_from_qc(
        quantum_circuit: QuantumCircuit,
        max_depth: int,
        coupling_map: Optional[Iterable[Tuple[int, int]]] = None,
        directed_coupling: bool = True,
) -> Node:
    new_state = Circuit(quantum_circuit.num_qubits, quantum_circuit.num_clbits).building_state(quantum_circuit)
    return Node(
        new_state,
        max_depth=max_depth,
        parent=None,
        coupling_map=coupling_map,
        directed_coupling=directed_coupling,
    )


def node_from_qc(quantum_circuit: QuantumCircuit, parent_node: Node, roll_out: bool) -> Node:
    if not isinstance(quantum_circuit, QuantumCircuit):
        raise TypeError("quantum_circuit must be a QuantumCircuit")
    new_state = Circuit(quantum_circuit.num_qubits, quantum_circuit.num_clbits).building_state(quantum_circuit)
    new_child = Node(
        new_state,
        max_depth=parent_node.max_depth,
        parent=parent_node,
        coupling_map=parent_node.coupling_map,
        directed_coupling=parent_node.directed_coupling,
    )
    if not roll_out:
        parent_node.children.append(new_child)
    return new_child


def sample_virtual_candidate(parent: Node, prob_choice: Dict[str, int]) -> Dict[str, Any]:
    """
    Sample ONE candidate expansion from `parent` WITHOUT appending it to the tree.
    This mirrors Node.define_children(..., stop_deterministic=False).
    """
    qc = parent.state.circuit.copy()
    stop = parent.stop_is_done
    gate_set = parent._make_gateset()

    def sample_once(local_prob_choice: Dict[str, int]) -> Tuple[Any, Any]:
        new_qc_fn, action = parent.state.get_legal_action(
            gate_set, parent.max_depth, local_prob_choice, stop
        )
        return new_qc_fn(qc), action

    new_qc, action = sample_once(prob_choice)

    if new_qc == "stop":
        return {
            "kind": "stop",
            "qc": parent.state.circuit.copy(),
            "action": action,
        }

    if new_qc is None:
        temporary_prob_choice = {"a": 50, "s": 50, "c": 0, "d": 0}
        new_qc, action = sample_once(temporary_prob_choice)

        if new_qc is None:
            temporary_prob_choice = {"a": 100, "s": 0, "c": 0, "d": 0}
            new_qc, action = sample_once(temporary_prob_choice)

    if isinstance(new_qc, QuantumCircuit):
        return {
            "kind": "child",
            "qc": new_qc,
            "action": action,
        }

    raise TypeError(
        f"Expected QuantumCircuit or 'stop', got {type(new_qc)} "
        f"(action={action}, value_repr={repr(new_qc)[:200]})"
    )


def materialize_virtual_candidate(
        parent: Node,
        candidate: Dict[str, Any],
        *,
        prior_value: Optional[float] = None,
) -> Node:
    kind = candidate["kind"]

    if kind == "stop":
        parent.isTerminal = True
        parent.stop_is_done = True
        parent.counter_cx = parent.state.circuit.count_ops().get("cx", 0)
        return parent

    if kind == "child":
        child = node_from_qc(candidate["qc"], parent_node=parent, roll_out=False)
        child.action = candidate.get("action")
        child.prior_value = prior_value
        parent.counter_cx = parent.state.circuit.count_ops().get("cx", 0)
        return child

    raise ValueError(f"Unknown candidate kind: {kind}")


# ============================================================
# Selection: Use UCB1
# ============================================================

def select(
    node: Node,
    exploration: float = 0.4,
    use_prior_in_ucb: bool = False,
    prior_ucb_weight: float = 0.0,
) -> Node:
    """
    Selection rule:
    - If every child has visits > 1: use UCB, optionally with an extra prior term
      score = Q + U + w * p / n_i
    - Otherwise: choose among unvisited children (visits == 0)
      the one with the highest prior_value
    """

    if len(node.children) == 0:
        raise ValueError("select() called on a node with no children")

    if all(child.visits >= 1 for child in node.children):
        log_visits = np.log(max(node.visits, 1))

        best_child = None
        best_score = -float("inf")

        for child in node.children:
            q_term = child.value / child.visits
            u_term = exploration * np.sqrt(log_visits / child.visits)

            p_term = 0.0
            if use_prior_in_ucb and child.prior_value is not None:
                p_term = prior_ucb_weight * child.prior_value / child.visits # pw/ni
                #p_term = prior_ucb_weight * child.prior_value   # pw

            score = q_term + u_term + p_term

            if score > best_score:
                best_score = score
                best_child = child

        return best_child

    # Otherwise, pick an unvisited child with highest prior_value
    unvisited = [child for child in node.children if child.visits == 0]
    if unvisited:
        with_prior = [child for child in unvisited if child.prior_value is not None]
        if with_prior:
            return max(with_prior, key=lambda c: c.prior_value)

        print("no prior, problem")
        return random.choice(unvisited)

    raise RuntimeError("Selection reached an unexpected state.")


# ============================================================
# EXPANSION: Random expansion and GNN-guided expansion
# ============================================================

def expand_random(node: Node, prob_choice: dict, stop_deterministic: bool) -> Node:
    new_node = node.define_children(prob_choice=prob_choice, stop_deterministic=stop_deterministic)
    if stop_deterministic:
        stop_node = node_from_qc(new_node.state.circuit, new_node, roll_out=False)
        stop_node.isTerminal = True
        return stop_node
    return new_node


def expand_gnn_guided_bulk(
    node: Node,
    *,
    prob_choice: Dict[str, int],
    branches,
    pw_C: float,
    pw_alpha: float,
    gnn_rank_function: Callable[[List[QuantumCircuit]], np.ndarray],
    gnn_candidate_pool_size: int,
    ignore_stop_in_guided: bool = True,
) -> Tuple[Node, int, int]:
    """
    Fill ALL currently available PW slots with the top GNN-ranked children.

    Assumption:
        gnn_rank_function returns fidelity directly, so HIGHER is better.

    Returns:
        chosen_child_for_current_iteration,
        n_children_added,
        n_candidates_ranked
    """
    slots_to_fill = pw_available_slots(node, branches, pw_C, pw_alpha)
    if slots_to_fill <= 0:
        return node, 0, 0

    pool_size = max(int(gnn_candidate_pool_size), int(slots_to_fill))

    existing_keys = {circuit_to_key(child.state.circuit) for child in node.children}
    virtual_candidates: List[Dict[str, Any]] = []
    qc_candidates: List[QuantumCircuit] = []

    attempts = 0
    max_attempts = max(pool_size * 8, pool_size + 16)

    while len(virtual_candidates) < pool_size and attempts < max_attempts:
        attempts += 1
        cand = sample_virtual_candidate(node, prob_choice)

        if cand["kind"] == "stop":
            if ignore_stop_in_guided:
                continue
            continue

        key = circuit_to_key(cand["qc"])
        if key in existing_keys:
            continue

        existing_keys.add(key)
        virtual_candidates.append(cand)
        qc_candidates.append(cand["qc"])

    if not virtual_candidates:
        child = expand_random(node, prob_choice=prob_choice, stop_deterministic=False)
        return child, 1, 1

    scores = np.asarray(gnn_rank_function(qc_candidates), dtype=float).reshape(-1)
    if scores.shape[0] != len(virtual_candidates):
        raise ValueError(
            f"gnn_rank_function returned {scores.shape[0]} scores for {len(virtual_candidates)} candidates."
        )

    order = np.argsort(-scores)

    added_children: List[Node] = []
    for idx in order[:slots_to_fill]:
        cand = virtual_candidates[int(idx)]
        prior_value = float(scores[int(idx)])
        child = materialize_virtual_candidate(
            node,
            cand,
            prior_value=prior_value,
        )
        added_children.append(child)

    if not added_children:
        child = expand_random(node, prob_choice=prob_choice, stop_deterministic=False)
        return child, 1, len(virtual_candidates)

    return added_children[0], len(added_children), len(virtual_candidates)


# ============================================================
# Rollout / evaluation / backpropagation
# ============================================================

def rollout(node: Node, steps: int, simulation_strategy) -> Node:
    new_node = node
    for _ in range(steps):
        if simulation_strategy and any(simulation_strategy.values()):
            if random.uniform(0, 1) >= 0.1:
                last_qubit_modified = new_node.state.circuit.data[-1][1].index
                new_node = new_node.simulation(simulation_strategy, qubit=last_qubit_modified)
            else:
                new_node = new_node.define_children(
                    prob_choice={"a": 100, "d": 0, "s": 0, "c": 0, "p": 0},
                    roll_out=True,
                    stop_deterministic=False,
                )
        else:
            new_node = new_node.define_children(
                prob_choice={"a": 100, "d": 0, "s": 0, "c": 0, "p": 0},
                roll_out=True,
                stop_deterministic=False,
            )
    return new_node


def evaluate(node: Node, evaluation_function) -> float:
    return node.state.evaluation(evaluation_function)


def backpropagate(node: Node, result: float) -> None:
    while node is not None:
        node.visits += 1
        node.value += result
        node = node.parent


def commit(current_node: Node, criteria: str) -> Node:
    return current_node.best_child(criteria=criteria)


def extract_best_path(root: Node, criteria: str) -> Tuple[List[QuantumCircuit], List[int], List[int], List[float], Node]:
    node = root
    qc_path: List[QuantumCircuit] = []
    children_counts: List[int] = []
    visits: List[int] = []
    values: List[float] = []

    while True:
        qc_path.append(node.state.circuit)
        children_counts.append(len(node.children))
        visits.append(node.visits)
        values.append(node.value)

        if node.isTerminal or len(node.children) == 0:
            break
        node = node.best_child(criteria=criteria)

    return qc_path, children_counts, visits, values, node


# ============================================================
# Main configurable MCTS
# ============================================================
def mcts(
    root: Node,
    budget: int,
    evaluation_function=None,
    criteria: str = "average_value",
    rollout_type: str = "classic",
    roll_out_steps: int = 0,
    simulation: bool = False,
    branches=False,
    choices: dict = None,
    epsilon: Optional[float] = None,
    stop_deterministic: bool = False,
    ucb_value: float = 0.4,
    pw_C: float = 1.0,
    pw_alpha: float = 0.3,
    verbose: bool = False,

    # evaluation mode
    evaluation_mode: str = "oracle",         # "oracle" | "gnn"
    gnn_value_function: Optional[Callable[[QuantumCircuit], float]] = None,

    # expansion mode
    expansion_mode: str = "random",          # "random" | "gnn_guided"
    gnn_rank_function: Optional[Callable[[List[QuantumCircuit]], np.ndarray]] = None,
    gnn_candidate_pool_size: int = 8,
    ignore_stop_in_guided: bool = True,

    # selection control
    prefer_unvisited_by_prior: bool = True,  # kept for compatibility
    use_prior_in_ucb: bool = False,
    prior_ucb_weight: float = 0.0,

    # coupling-map plumbing (optional override if root was created without one)
    coupling_map: Optional[Iterable[Tuple[int, int]]] = None,
    directed_coupling: bool = True,
) -> Dict[str, Any]:
    """
    Configurable backend-basis MCTS with:

    Expansion options:
      - expansion_mode="random"
      - expansion_mode="gnn_guided"

    Evaluation options:
      - evaluation_mode="oracle" : uses evaluation_function
      - evaluation_mode="gnn"    : uses gnn_value_function as ONLY evaluator

    Optional prior term in visited-child selection:
      score = Q + U + w * p / n_i
    where:
      - w = prior_ucb_weight
      - p = child.prior_value
      - n_i = child.visits

    If use_prior_in_ucb=False, behavior is exactly the same as before.
    """

    if choices is None:
        choices = {'a': 50, 'd': 10, 's': 20, 'c': 20, 'p': 0}

    if evaluation_mode not in {"oracle", "gnn"}:
        raise ValueError("evaluation_mode must be 'oracle' or 'gnn'.")

    if expansion_mode not in {"random", "gnn_guided"}:
        raise ValueError("expansion_mode must be 'random' or 'gnn_guided'.")

    if evaluation_mode == "oracle" and evaluation_function is None:
        raise ValueError("evaluation_mode='oracle' requires evaluation_function.")
    if evaluation_mode == "gnn" and gnn_value_function is None:
        raise ValueError("evaluation_mode='gnn' requires gnn_value_function.")
    if expansion_mode == "gnn_guided" and gnn_rank_function is None:
        raise ValueError("expansion_mode='gnn_guided' requires gnn_rank_function.")

    if coupling_map is not None:
        root.coupling_map = normalize_coupling_map(coupling_map, directed_coupling)
        root.directed_coupling = bool(directed_coupling)

    prob_choice = {'a': 100, 'd': 0, 's': 0, 'c': 0}
    original_root = root

    if verbose:
        print("Root Node:\n", root)

    oracle_eval_calls = 0
    gnn_eval_calls = 0
    gnn_rank_batches = 0
    gnn_rank_candidates_scored = 0

    def evaluate_node(node: Node) -> float:
        nonlocal oracle_eval_calls, gnn_eval_calls

        if evaluation_mode == "oracle":
            oracle_eval_calls += 1
            return float(evaluation_function(node.state.circuit))

        if node.prior_value is not None:
            return float(node.prior_value)

        gnn_eval_calls += 1
        val = float(gnn_value_function(node.state.circuit))
        node.prior_value = val
        return val

    best_overall_value = evaluate_node(root)
    best_overall_qc = root.state.circuit.copy()
    root.visits = max(root.visits, 1)

    n_qubits = len(root.state.circuit.qubits)

    if simulation:
        qubit_ngrams_counter = {q: Counter() for q in range(n_qubits)}
        quality_results_by_qubit = defaultdict(lambda: defaultdict(list))
        n = 2
    else:
        qubit_ngrams_counter, quality_results_by_qubit = None, None
        n = None

    for epoch_counter in range(budget):
        current_node = root

        if current_node.visits > budget / 20 and len(current_node.children) > 2:
            if epsilon is not None:
                if random.uniform(0, 1) >= epsilon:
                    root = commit(current_node, criteria)
            else:
                root = commit(current_node, criteria)

            if verbose:
                print("Committed to", root)
            current_node = root

        while (
            not current_node.isTerminal
            and current_node.is_fully_expanded(branches=branches, pw_C=pw_C, pw_alpha=pw_alpha)
        ):
            current_node = select(
                current_node,
                exploration=ucb_value,
                use_prior_in_ucb=use_prior_in_ucb,
                prior_ucb_weight=prior_ucb_weight,
            )
            if verbose:
                print("Selection:", current_node)

        if not current_node.isTerminal:
            if expansion_mode == "random":
                current_node = expand_random(
                    current_node,
                    prob_choice=prob_choice,
                    stop_deterministic=stop_deterministic,
                )
            else:
                current_node, n_added, n_ranked = expand_gnn_guided_bulk(
                    current_node,
                    prob_choice=prob_choice,
                    branches=branches,
                    pw_C=pw_C,
                    pw_alpha=pw_alpha,
                    gnn_rank_function=gnn_rank_function,
                    gnn_candidate_pool_size=gnn_candidate_pool_size,
                    ignore_stop_in_guided=ignore_stop_in_guided,
                )
                gnn_rank_batches += 1
                gnn_rank_candidates_scored += int(n_ranked)

            if verbose:
                print("Expanded / chosen node:\n", current_node)

        if not current_node.isTerminal:
            if isinstance(roll_out_steps, int):
                leaf_node = rollout(current_node, steps=roll_out_steps, simulation_strategy=quality_results_by_qubit)
                result = evaluate_node(leaf_node)

                if result > best_overall_value:
                    best_overall_value = result
                    best_overall_qc = leaf_node.state.circuit.copy()

                if roll_out_steps > 1 and rollout_type != "classic":
                    node_to_evaluate = leaf_node
                    result_list = [result]
                    for _ in range(roll_out_steps):
                        if node_to_evaluate.parent is None:
                            break
                        result_list.append(evaluate_node(node_to_evaluate.parent))
                        node_to_evaluate = node_to_evaluate.parent

                    if rollout_type == "max":
                        result = max(result_list)
                    elif rollout_type == "mean":
                        result = sum(result_list) / len(result_list)
                    else:
                        raise NotImplementedError(f"Rollout type '{rollout_type}' is not implemented.")
            else:
                raise TypeError("roll_out_steps must be an integer")
        else:
            result = evaluate_node(current_node)
            if result > best_overall_value:
                best_overall_value = result
                best_overall_qc = current_node.state.circuit.copy()

        if verbose:
            print("Reward:", result)

        backpropagate(current_node, result)

        if simulation:
            qubit_ngrams_counter = update_ngrams(current_node.state.circuit, n, qubit_ngrams_counter)
            quality_results_by_qubit = update_conditional_results(
                qubit_ngrams_counter, quality_results_by_qubit, result
            )

        if current_node.tree_depth == 2 * n_qubits:
            prob_choice = choices

    qc_path, children_counts, visits, values, final_node = extract_best_path(original_root, criteria)

    return {
        "qc": qc_path,
        "children": children_counts,
        "visits": visits,
        "value": values,
        "final_path_qc": final_node.state.circuit,
        "best_overall_qc": best_overall_qc,
        "best_overall_value": best_overall_value,
        "evaluation_mode": evaluation_mode,
        "expansion_mode": expansion_mode,
        "oracle_eval_calls": oracle_eval_calls,
        "gnn_eval_calls": gnn_eval_calls,
        "gnn_rank_batches": gnn_rank_batches,
        "gnn_rank_candidates_scored": gnn_rank_candidates_scored,
        "use_prior_in_ucb": use_prior_in_ucb,
        "prior_ucb_weight": prior_ucb_weight,
    }
